/**
 * Server mirror of @savvy/core deal streak config.
 */

const DEAL_STREAK_MIN_QUALIFY_INTERVAL_MS = 4 * 60 * 60 * 1000;
const DEAL_STREAK_CONTRACT_MILESTONE = 5;
const NUKE_CATEGORY_CONSECUTIVE_TARGET = 30;
const QUANTUM_NUKE_DEAL_STREAK_TARGET = 30;
const DEAL_STREAK_HISTORY_LIMIT = 100;
const QUALIFYING_DEAL_RECORDED_EVENT = 'f10:qualifying-deal-recorded';

const DEAL_STREAK_SOURCE_TYPES = Object.freeze(['auction_won', 'deal_purchase']);

module.exports = {
  DEAL_STREAK_MIN_QUALIFY_INTERVAL_MS,
  DEAL_STREAK_CONTRACT_MILESTONE,
  NUKE_CATEGORY_CONSECUTIVE_TARGET,
  QUANTUM_NUKE_DEAL_STREAK_TARGET,
  DEAL_STREAK_HISTORY_LIMIT,
  QUALIFYING_DEAL_RECORDED_EVENT,
  DEAL_STREAK_SOURCE_TYPES,
};
