name: 🔄 Auto-Merge AI Fixes

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔍 Check PR Requirements
        id: check-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = context.payload.pull_request;
            
            // Check if this is an AI-generated PR
            const isAiGenerated = pr.title.includes('AI Fix') || 
                                 pr.labels.some(label => label.name === 'ai-generated');
            
            if (!isAiGenerated) {
              console.log('Not an AI-generated PR, skipping auto-merge');
              core.setOutput('should_merge', 'false');
              return;
            }
            
            // Check if PR is approved (if required)
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            const hasApproval = reviews.some(review => review.state === 'APPROVED');
            
            // Check if CI checks are passing
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });
            
            const allChecksPassing = checks.check_runs.every(check => 
              check.conclusion === 'success' || check.conclusion === 'skipped'
            );
            
            // Auto-merge criteria
            const shouldMerge = pr.mergeable && 
                               pr.mergeable_state === 'clean' && 
                               allChecksPassing &&
                               (hasApproval || pr.draft === false); // Auto-merge if not draft and checks pass
            
            console.log(`AI PR #${pr.number} merge criteria:`);
            console.log(`- Mergeable: ${pr.mergeable}`);
            console.log(`- State: ${pr.mergeable_state}`);
            console.log(`- Checks: ${allChecksPassing}`);
            console.log(`- Approved: ${hasApproval}`);
            console.log(`- Draft: ${pr.draft}`);
            
            core.setOutput('should_merge', shouldMerge.toString());
      
      - name: 🔄 Auto-Merge PR
        if: steps.check-pr.outputs.should_merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = context.payload.pull_request;
            
            console.log(`🤖 Auto-merging AI-generated PR #${pr.number}`);
            
            try {
              // Merge the PR
              const { data: mergeResult } = await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                commit_title: `🤖 Auto-merge: ${pr.title}`,
                merge_method: 'squash'
              });
              
              console.log(`✅ Successfully merged PR #${pr.number}`);
              
              // Comment on PR
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: |
                  🤖 **Auto-Merged by AI System**
                  This AI-generated fix has been automatically merged and deployed.
                  **Merge Details:**
                  - ✅ Merged: ${mergeResult.merged}
                  - ✅ SHA: `${mergeResult.sha}`
                  - ✅ Method: ${mergeResult.merge_method}
                  The related issue will be automatically closed.
              });
              
            } catch (error) {
              console.error('❌ Auto-merge failed:', error);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: |
                  ❌ **Auto-Merge Failed**
                  The automated merge failed:
                  ```
                  ${error.message}
                  ```
                  Please review and merge manually.
              });
            }
      
      - name: 🔒 Close Related Issues
        if: steps.check-pr.outputs.should_merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = context.payload.pull_request;
            
            // Extract issue numbers from PR body
            const issueMatches = pr.body.match(/#(\d+)/g);
            
            if (issueMatches) {
              for (const match of issueMatches) {
                const issueNumber = parseInt(match.replace('#', ''));
                
                try {
                  // Close the issue
                  await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    state: 'closed'
                  });
                  
                  // Comment on the issue
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    body: |
                      ✅ **Bug Fixed & Deployed**
                      This issue has been automatically fixed and deployed by the AI development team.
                      **Fix Details:**
                      - 🤖 **PR:** #${pr.number}
                      - ✅ **Status:** Merged and deployed
                      - 🚀 **Deployed:** ${new Date().toISOString()}
                      The fix is now live in production. Thank you for reporting this issue!
                  });
                  
                  console.log(`✅ Closed related issue #${issueNumber}`);
                  
                } catch (error) {
                  console.error(`❌ Failed to close issue #${issueNumber}:`, error);
                }
              }
            }
      
      - name: 📊 Merge Summary
        if: steps.check-pr.outputs.should_merge == 'true'
        run: |
          echo "🤖 AI Auto-Merge Summary"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Merged: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Related issues have been automatically closed"






